### ISSUE TITLE
Error while trying to getbookeddates

### ISSUE THREAD

**Issue by endrianus** [tiipiik/OctoberCMS-RoomBooking#14]
Hello. 

when I first book date on front end in specific room, then returned back to booking page it returned this error. From the trace, it said that getbookeddates returned error. what's the solution ? 

please kindly find the attached file.

![screen shot 2017-02-21 at 6 57 31 am](https://cloud.githubusercontent.com/assets/16950480/23145728/21921ee0-f803-11e6-9a31-d2ce1bf3ce05.png)
![screen shot 2017-02-21 at 6 57 39 am](https://cloud.githubusercontent.com/assets/16950480/23145729/2196c558-f803-11e6-83ea-70a44ba4dfe7.png)

**Comment by tiipiik** [comment]
Did you manage to fix your issue ? I'm really sorry for the delay. Did you configure the components properly ?

**Comment by kubektkd** [comment]
Hi, I have the same problem, but only when I add reservation in backend.

I noticed that it is because of wrong date format of arrival and departure dates.
When adding a new reservation, I select only date in the arrival and departure fields, but after save in collumns view date with time is shown.

How can I format this date,  that it will be adding to database only date without time?

Please help.

**Comment by mabasic** [comment]
I have fixed this in this PR https://github.com/tiipiik/OctoberCMS-RoomBooking/pull/16
